language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "pluto-atom-4-github"

jdk: openjdk10

script:
  - mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'
